// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kukmucdsvjbfrgjbhlzg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1a211Y2RzdmpiZnJnamJobHpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1OTAwNTMsImV4cCI6MjA2NDE2NjA1M30.XAEEaqs9mSsLM3zR5qoz6D2DEyuFXj53wxKnN9ORTzE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);